export const mockApiMap: Record<
  string,
  (params: Record<string, any>) => Promise<Record<string, any>>
> = {
  fetchVatInfo: async ({ companyName }) => {
    console.log("I get here");
    
    await new Promise((res) => setTimeout(res, 1000));
    return {
      vatNumber: `BG-123456-${companyName?.slice(0, 2).toUpperCase() ?? "XX"}`
    };
  },

  fetchUserInfo: async ({ firstName }) => {
    console.log("I get here");

    await new Promise((res) => setTimeout(res, 600));
    return {
      bio: `Autogenerated bio for ${firstName}`,
      gender: "Other"
    };
  }
};
